### ISSUE TITLE
ImportError: No module named ExodusModel

### ISSUE THREAD

**Issue by hefnymah** [cpgr/em2ex#1]
Hi Chris,
I am trying to use this fantisitc code to convert eclipse into exodus. after add python path to my bashrc file i run the code but i got the following error (as the attached images)

<ImportError: No module named ExodusMode>
thanks so much for your help to fix to point in advance
Cheers, mahmoud
![Screenshot from 2019-05-31 20-55-16](https://user-images.githubusercontent.com/31239387/58728099-70d16a80-83e6-11e9-8a75-738c9f23b4fd.png)

**Comment by cpgr** [comment]
Oops, I was relying on my em2ex folder being in my path. I think that I have fixed this in https://github.com/cpgr/em2ex/commit/378abafb322c62ecea68d6f655b0aea7772d1a57 so if you fetch the latest version it should work.

Just a quick note that there is still some functionality that I am adding (like dealing with inactive cells and faults), so it isn't perfect at the moment

**Comment by hefnymah** [comment]
thanks so much for your update.
