### ISSUE TITLE
Material properties

### ISSUE THREAD

**Issue by raincoder87** [cpgr/em2ex#32]
Dear Chris,
As em2ex keep reservoir model material properties like porosity/permeability when it converts from eclipse format into exodus format. I am kindly wondering about the best way to get these material properties of the elements from exodus file when we read in moose [porousflow M.], instead of typing one single value for porosity/ permeability,..etc within the input file.
Thanks so much
Sam

**Comment by cpgr** [comment]
This is pretty easy once you have the model converted to exodus format. I wrote a brief tutorial on it here https://mooseframework.inl.gov/modules/porous_flow/heterogeneous_models.html

**Comment by raincoder87** [comment]
That's really awesome, thanks so much Chriss

**Comment by cpgr** [comment]
No worries. Let me know if you run into any issues.

**Comment by raincoder87** [comment]
Thanks so much, Chris, for your offer. much appreciated 
I have another one and I am sorry for being so simple in my questions but I am starting to learn moose.
what would the best way to position two points within the realistic reservoir model exodus file (like the one presented here form SAIGUP project )? these points are to simulate the injection and production boreholes. do I have to create other input files for this step?
 Thanks you very much for your help in advance,
Best, Sam

**Comment by cpgr** [comment]
You can do this in MOOSE - check out https://mooseframework.inl.gov/modules/porous_flow/sinks.html for some examples. There should be plenty of input files in the test suite that show how to do this.

**Comment by raincoder87** [comment]
these keywords and link will be of great importance as a starting point.
thanks a lot for your guides.
