### ISSUE TITLE
Reversed depth after model conversion 

### ISSUE THREAD

**Issue by leoforeal** [cpgr/em2ex#36]
Hallo!

While using this code I successfully converted a Petel/Eclipse (.grdecl files) to Exodus II (.e),
but as I opened the model with Paraview, I realized the sign of z-coordinate is automatically reversed to positive values.
for example: 
x: 100 y: 100 z: -100 in Petrel model becomes 
x: 100 y: 100 z: +100 after the conversion.

Does anyone know what could be the reason behind this or more specifically how i could retain the negative z value after the conversion?

**Comment by cpgr** [comment]
I'm on holiday without a computer so can't try it,but I think of you pass `--flip` when you run it will flip the sign of the Z coordinates
