### ISSUE TITLE
missing elemental properties in block array

### ISSUE THREAD

**Issue by leoforeal** [cpgr/em2ex#40]
Hallo,

It never happened before but only with this .grdecl file I have. 

So I double checked that all material properties KEYWORD are included, namely actnum, poro, permx, permy and permz.
But somehow after the em2ex conversion, viewed in paraview, only "actnum", "poro" and "perm" are seen. Do you know why the permx, permy and permz have then all been somehow merged/stored in one material property "perm" instead of being seperated?

Do you have any idea what might lead to that?

![Bildschirmfoto 2023-12-04 um 22 49 45](https://github.com/cpgr/em2ex/assets/138106081/ece90a12-75a8-49cd-a240-b65e4985bb03)

Thanks so much in advance!

**Comment by cpgr** [comment]
Paraview might have combined them into a single vector? When you show perm, the box next to it might allow you to select x, y, and z components? Hopefully it is just that!

**Comment by cpgr** [comment]
Like this:

![Screenshot 2023-12-05 at 9 02 16 am](https://github.com/cpgr/em2ex/assets/7664823/f80bdd31-40bf-45f0-921e-7293bba3ad09)

**Comment by leoforeal** [comment]
Hi,

thanks a lot for the quick response!
I just checked again, the properties are totally still there, but somehow paraview by default display the magnitude of all perm vectors. 

So problem solved :)
